### ISSUE TITLE
Cursor y value inaccurate on OSX

### ISSUE THREAD

**Issue by thedaniel** [SLiV9/epicinium#23]
I'm on OSX Sierra with a 13" rMBP - In the menus and lobby the click target is lower than the pointer - at the top of the screen it seems accurate, but by the middle of the screen it's off by tens of pixels. 

To explain in a different way, if I move the cursor over PLAY in the opening menu, CREDITS is highlighted.

**Comment by UnarmedLad** [comment]
Hey Daniel, thank you for your report. I think this is related to issue #19. Have you tried setting the "width" and "height" in settings.json to your screen's native resolution? Nevertheless, this shouldn't happen in versions > 0.6.0 as the game should detect incorrect resolution settings and override. We'll try to reproduce.

**Comment by UnarmedLad** [comment]
@thedaniel Unfortunately, we haven't been able to reproduce this yet. However, we've changed the way the display resolution is detected in version 0.8.0 (`SDL_GetDisplayBounds` over `SDL_GetDesktopDisplayMode`, and `SDL_WINDOW_FULLSCREEN_DESKTOP` over `SDL_WINDOW_FULLSCREEN` on OS X).

Could you check whether the issue is fixed in this version? If it's not, could you tell me your screen's native resolution, what you have in your `settings.json` and what shows up in `logs/main.info.log` when you start the game?

**Comment by thedaniel** [comment]
Fixed in 0.8.0

![](https://media.giphy.com/media/ENagATV1Gr9eg/giphy.gif)
